# Generated by Django 2.2.1 on 2019-05-24 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_ajax', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrudUser',
        ),
    ]
